services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitrescue-rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: rabbitrescue
      RABBITMQ_DEFAULT_PASS: rabbitrescue
      RABBITMQ_DEFAULT_VHOST: rabbitrescue

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq-data: